[package]
name = "lint-docs"
version = "0.1.0"
edition = "2021"
description = "A script to extract the lint documentation for the rustc book."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-literal-escaper = "0.0.5"
serde_json.workspace = true
tempfile.workspace = true
walkdir = "2.3.1"
