[package]
name = "rustc_symbol_mangling"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
punycode = "0.4.0"
rustc-demangle.workspace = true
rustc_abi = { path = "../rustc_abi" }
rustc_data_structures = { path = "../rustc_data_structures" }
rustc_errors = { path = "../rustc_errors" }
rustc_hashes = { path = "../rustc_hashes" }
rustc_hir = { path = "../rustc_hir" }
rustc_middle = { path = "../rustc_middle" }
rustc_session = { path = "../rustc_session" }
rustc_span = { path = "../rustc_span" }
tracing.workspace = true
# tidy-alphabetical-end
