[package]
name = "run_make_support"
version = "0.2.0"
edition = "2021"

[dependencies]
bstr = "1.6.0"
object = "0.34.0"
similar = "2.5.0"
wasmparser = "0.118.2"
regex = "1.8" # 1.8 to avoid memchr 2.6.0, as 2.5.0 is pinned in the workspace
gimli = "0.31.0"
build_helper = { path = "../build_helper" }
