# This workflow runs spellcheck job

name: Spellcheck
on:
  pull_request:
    branches:
      - "**"

jobs:
  spellcheck:
    name: run spellchecker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4

      - name: check typos
        # sync version with src/tools/tidy/src/ext_tool_checks.rs in spellcheck_runner
        uses: crate-ci/typos@v1.34.0
        with:
          # sync target files with src/tools/tidy/src/ext_tool_checks.rs in check_impl
          files: ./compiler ./library ./src/bootstrap ./src/librustdoc
          config: ./typos.toml
